# Generated by Django 5.2 on 2025-06-11 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_user_username_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_played',
            field=models.BooleanField(default=False),
        ),
    ]
