# Generated by Django 5.2 on 2025-09-19 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_has_played'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='freelance_index',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
