#version: '3.8'

services:
  ftp-redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  ftp-backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file: ./backend/.env
    depends_on:
      - ftp-redis

  ftp-frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    depends_on:
      - ftp-backend
    environment:
      - REACT_APP_BACKEND_ROOT=ftp.0xcad.dev:8000

