#version: '3.8'

services:
  ftp-redis:
    image: "redis:alpine"
    container_name: ftp-redis

  ftp-backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    env_file: ./backend/.env
    depends_on:
      - ftp-redis
    container_name: ftp-backend
    restart: unless-stopped

  ftp-frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
    depends_on:
      - ftp-backend
    env_file: ./frontend/.env
    container_name: ftp-frontend

  #ftp-frontend:
  #  image: node:alpine
  #  container_name: ftp-frontend
  #  working_dir: /app
  #  volumes:
  #    - ./frontend/build/client:/app:ro
  #  command: sh -c "npm install -g http-server && http-server -p 3000 ."
  #  restart: unless-stopped

networks:
  default:
      name: 0xcad-dockernet
