# Generated by Django 5.2 on 2025-06-12 18:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0002_playinstance_audience_playinstance_join_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playinstance',
            old_name='current_game_start',
            new_name='end_time',
        ),
        migrations.AddField(
            model_name='playinstance',
            name='remaining_time',
            field=models.DurationField(default=datetime.timedelta(seconds=300)),
        ),
    ]
