# Generated by Django 5.2 on 2025-07-17 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0003_rename_current_game_start_playinstance_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playinstance',
            name='stream_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
