# Generated by Django 5.2 on 2025-09-19 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0004_playinstance_stream_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playinstance',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='playinstance',
            name='remaining_time',
        ),
    ]
