# Generated by Django 5.2 on 2025-04-26 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='user_name',
            new_name='username',
        ),
    ]
