# Generated by Django 5.2 on 2025-06-05 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_rename_user_name_chatmessage_username'),
        ('play', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='timestamp',
            new_name='created',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='username',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='play_instance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='play.playinstance'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
