# Generated by Django 5.2 on 2025-09-18 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_rename_timestamp_chatmessage_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='system',
            field=models.BooleanField(default=False, help_text='Is this a system message?'),
        ),
    ]
