# Generated by Django 5.2 on 2025-07-10 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('play', '0003_rename_current_game_start_playinstance_end_time_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the item category.', max_length=50, unique=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of this category in the list, lower numbers appear first.')),
            ],
            options={
                'verbose_name_plural': 'Item Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='items/')),
                ('cost', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('data', models.JSONField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField(default=0, help_text='How many of this item are available per play instance.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of this item in the list, lower numbers appear first.')),
                ('category', models.ForeignKey(blank=True, help_text='The category this item belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='store.itemcategory')),
            ],
            options={
                'ordering': ['category__order', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ItemPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchased_items', to='store.item')),
                ('play_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchased_items', to='play.playinstance')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_purchased_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['play_instance', 'item__category__order', 'item__order', 'item__name'],
            },
        ),
    ]
