# Generated by Django 5.2 on 2025-09-08 19:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('play', '0004_playinstance_stream_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the item category.', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, max_length=15, null=True)),
                ('order', models.PositiveIntegerField(blank=True, help_text='Order of this category in the list, lower numbers appear first.', null=True)),
                ('item_type', models.CharField(blank=True, choices=[('user', 'User'), ('play', 'Play')], max_length=10, null=True)),
            ],
            options={
                'verbose_name_plural': 'Item Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='items/')),
                ('cost', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('item_type', models.CharField(blank=True, choices=[('user', 'User'), ('play', 'Play')], help_text='Buy it for yourself or for the play.', max_length=10, null=True)),
                ('quantity', models.PositiveIntegerField(blank=True, default=0, help_text='How many of this item are available per play instance.', null=True)),
                ('order', models.PositiveIntegerField(blank=True, default=0, help_text='Order of this item in the list, lower numbers appear first.', null=True)),
                ('category', models.ForeignKey(blank=True, help_text='The category this item belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='store.itemcategory')),
            ],
            options={
                'ordering': ['category__order', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ItemPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='When the item was purchased.')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchased_items', to='store.item')),
                ('play_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchased_items', to='play.playinstance')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_purchased_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['play_instance', 'item__category__order', 'item__order', 'item__name'],
            },
        ),
        migrations.CreateModel(
            name='StripeCheckoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(help_text='The unique ID of the Stripe Checkout session.', max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the checkout session was created.')),
                ('completed', models.BooleanField(default=False, help_text='Whether the checkout session has been completed.')),
                ('user', models.ForeignKey(help_text='The user who initiated the checkout.', on_delete=django.db.models.deletion.CASCADE, related_name='stripe_checkouts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
