# Generated by Django 5.2 on 2025-07-18 20:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeCheckoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(help_text='The unique ID of the Stripe Checkout session.', max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the checkout session was created.')),
                ('completed', models.BooleanField(default=False, help_text='Whether the checkout session has been completed.')),
                ('user', models.ForeignKey(help_text='The user who initiated the checkout.', on_delete=django.db.models.deletion.CASCADE, related_name='stripe_checkouts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
