# Generated by Django 5.2 on 2025-07-10 19:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempurchase',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='When the item was purchased.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Order of this item in the list, lower numbers appear first.', null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='How many of this item are available per play instance.', null=True),
        ),
    ]
